global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'railway-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['hire-smart-backend-production.up.railway.app:443']
    scheme: https
